name = "server"
main = "src/index.ts"
compatibility_date = "2024-12-13"

[[d1_databases]]
database_id = "a6e54aed-340c-4495-9010-6e679c83bc45"
binding = "DB"
database_name = "idp-db-preview"
migrations_dir = "drizzle"

[[env.production.d1_databases]]
database_id = "7b42a115-ebac-47c9-9388-759082eb0d22"
binding = "DB"
database_name = "idp-db"
migrations_dir = "drizzle"
