name = "idp-preview"
main = "src/index.ts"
compatibility_date = "2024-12-13"

[dev]
port = 8787

[vars]
ALLOW_ORIGIN = "*"
GITHUB_APP_ID = "387915"
GITHUB_APP_INSTALLID = "41674415"
ENV = "development"

# IDP_SESSIONとCACHEを同じKVに指定するが、場合によってはセキュアリポジトリとキャッシャーを分ける可能性があるため別のバインドをしておく

[[kv_namespaces]]
binding = "IDP_SESSION"
id = "dev"              # dev なので仮の ID を指定

[[kv_namespaces]]
binding = "CACHE"
id = "dev"        # dev なので仮の ID を指定

[[d1_databases]]
binding = "DB"
database_id = "dev"            # dev なので仮の ID を指定
database_name = "idp-db-local"
migrations_dir = "drizzle"

# --- Preview ---

[env.preview]
name = "idp-server-preview"

[env.preview.vars]
ALLOW_ORIGIN = "*"
GITHUB_APP_ID = "387915"
GITHUB_APP_INSTALLID = "41674415"
GITHUB_OAUTH_ID = "Iv1.3fef0e17322d38ce"
ENV = "preview"

[[env.preview.routes]]
pattern = "api-preview.id.maximum.vc"
custom_domain = true

[[env.preview.d1_databases]]
database_id = "a6e54aed-340c-4495-9010-6e679c83bc45"
binding = "DB"
database_name = "idp-db-preview"
migrations_dir = "drizzle"

[[env.preview.kv_namespaces]]
binding = "IDP_SESSION"
id = "8566bd47321c43cab679ab65bb60e38b"

[[env.preview.kv_namespaces]]
binding = "CACHE"
id = "8566bd47321c43cab679ab65bb60e38b"

# --- Production ---

[env.production]
name = "idp-server"

[env.production.vars]
ALLOW_ORIGIN = "https://id.maximum.vc"
GITHUB_APP_ID = "387915"
GITHUB_APP_INSTALLID = "41674415"
GITHUB_OAUTH_ID = "Iv1.3fef0e17322d38ce"
ENV = "production"

[[env.production.routes]]
pattern = "api.id.maximum.vc"
custom_domain = true

[[env.production.d1_databases]]
database_id = "7b42a115-ebac-47c9-9388-759082eb0d22"
binding = "DB"
database_name = "idp-db"
migrations_dir = "drizzle"

[[env.production.kv_namespaces]]
binding = "IDP_SESSION"
id = "0cd11121be304250a5246b2c1a5e185d"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "0cd11121be304250a5246b2c1a5e185d"
