const FLAGS_DEFAULT = {
	ENABLE_LOGIN: true,
	ENABLE_OAUTH_REGISTRATION: true,
	ENABLE_CERTIFICATION: true,
	ENABLE_CALENDAR: true,
	ENABLE_INVITE: false,
};

export const DEV_FLAGS = {
	...FLAGS_DEFAULT,
	ENABLE_INVITE: true,
};

export const PROD_FLAGS = {
	...FLAGS_DEFAULT,
};
