name: Cron Trigger

on:
  # debug
  push:
    branches:
      - fix/cron
  schedule:
    # 毎日 03:00 JST
    - cron: 0 3 * * *
      timezone: Asia/Tokyo
    # 5/1 00:00 JST
    - cron: 0 0 1 5 *
      timezone: Asia/Tokyo

permissions:
  contents: read

jobs:
  run-cron:
    name: ${{ github.event.schedule }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - api.id.maximum.vc
          - api-preview.id.maximum.vc
    steps:
      - name: Setup Trigger Utility
        run: |
          echo << EOF > trigger
          #!/bin/bash
          task="$1"
          curl --fail-with-body --show-error -X POST "https://${{ matrix.host }}/cron/${task}" -H "X-Cron-Trigger-Token: ${{ secrets.CRON_TOKEN }}"
          EOF
          chmod +x trigger

      - name: Remove Expired Access Token (0 3 * * *)
        if: github.event.schedule == '0 3 * * *' || github.event_name == 'push'
        run: ./trigger remove-expired-access-token

      - name: Remove Member Role (0 0 1 5 *)
        if: github.event.schedule == '0 0 1 5 *'
        run: ./trigger remove-member-role
