name: Cron Trigger

on:
  schedule:
    # 毎日 03:00 JST
    - cron: 0 3 * * *
      timezone: Asia/Tokyo
    # 5/1 00:00 JST
    - cron: 0 0 1 5 *
      timezone: Asia/Tokyo

permissions:
  contents: read

jobs:
  run-cron:
    name: ${{ github.event.schedule }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - api.id.maximum.vc
          - api-preview.id.maximum.vc
    steps:
      - name: Run
        run: |
          # [HOST]/cron?cron=[schedule] にリクエストを送る
          curl --fail-with-body --show-error -X POST "https://${{ matrix.host }}/cron/trigger" -d "cron=${{ github.event.schedule }}" -H "X-Cron-Trigger-Token: ${{ secrets.CRON_TOKEN }}"
